import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const hello = trpc.hello.useQuery({ text: "Mati!" });
	const user = trpc.getUserById.useQuery({ text: "1" });
	if (!hello.data) {
		return <div>Loading...</div>;
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div>{hello.data.greeting}</div>

				{user && user.data?.name}
			</main>
		</>
	);
}
